### ISSUE TITLE
Connect Quali to Azure cloud.

### ISSUE THREAD

**Issue by rodriggj** [rodriggj/quali-demo#28]

**Comment by rodriggj** [comment]
On 23 Nov '22 Another working session was conducted: 

# Attendees:

# Goals:

# Accomplishments:

# Next Steps:

**Comment by rodriggj** [comment]
Notes: 

1. Chris provided Rajesh B. with a `yaml` file for a Deployment. 

```yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec: 
   replicas: 1
   strategy: 
       type: Rolling Update
   selector: 
       matchLabels: 
          app: ubuntu
   template: 
        metadata: 
             namespace: default 
                # labels: 
                #    app: ubuntu
                #    aadpodidbinding: torqueidentity
        spec: 
          # serviceAccountName: oidc
          containers: 
             - name: ubuntu
               image: ubuntu
               imagePullPolicy: IfNotPresent

```
